accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import(signup)

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home")),name=("main")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (ReceiptListView)
from receipts.views import (ReceiptCreateView)
from receipts.views import (ExpenseCategoryListView)
from receipts.views import (AccountListView)
from receipts.views import (ExpenseCategoryCreateView)
from receipts.views import (AccountCreateView)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("categories/", ExpenseCategoryListView.as_view(), name="expense_category"),
    path("account/", AccountListView.as_view(), name="account"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name="list_categories"),
    path("account/create/", AccountCreateView.as_view(), name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, related_name="categories", null=True)
    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length=100, null=True)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, related_name="accounts")
    def __str__(self):
        return self.name

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(default=timezone.now)
    purchaser = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, related_name="receipts", null=True)
    category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE, related_name="receipts")
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="receipts", null=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        context = {"form": form}
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect ("home")
    else:
        form = UserCreationForm(request.POST)
        context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from receipts.models import Receipt, ExpenseCategory, Account
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
# Create your views here.

class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    content_object_name = "receipt"
    template_name = "receipt.html"
    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "create.html"
    fields = ["vendor","total","tax","date", "category","account"]
    def form_valid(self, form):
        item = form.save(commit=False)
        item.user_property = self.request.user
        item.save()
        return redirect("home")

class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    content_object_name = "expensecategory"
    template_name = "category.html"
    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    content_object_name = "account"
    template_name = "account.html"
    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "create_category.html"
    fields = ["name"]
    success_url = reverse_lazy("expense_category")
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "c_account.html"
    fields = ["name", "number"]
    success_url = reverse_lazy("account")
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Expenses</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Expenses</a>
        </li>
        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Create Category</a>
          </li>
          <li>
            <a href="{% url 'create_account' %}">Create Account</a>
          </li>
        {% else %}
          <li>
            <a href="{% url 'login' %}">Login</a>
          </li>
          <li>
            <a href="{% url 'signup' %}">Signup</a>
          </li>

        {% endif %}
    </nav>
    {% block pagination%}
    {% endblock pagination %}
  </header>
  {% block content %}
  {% endblock content %}
</body>

</html>

receipts/templates/account.html
{%extends 'base.html'%}
{%block content%}
<main>
    <h1>Account</h1>
    <table>
        <thead>
            <tr>
                <td>Name</td>
                <td>Number</td>
                <td>Number of Receipts</td>
            </tr>
        <thead>
        <tbody>
            {%for acc in account_list.all %}
                <tr>
                    <td> {{acc.name}} </td>
                    <td> {{acc.number}} </td>
                    <td> {{acc.receipts.all|length}} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{%endblock content%}

receipts/templates/c_account.html
<!doctype html>
<html>
    <head>
        <title>Expenses</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create Account</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/category.html
{%extends 'base.html'%}
{%block content%}
<main>
    <h1>Expense</h1>
    <table>
        <thead>
            <tr>
                <td>Name</td>
                <td>Number of Receipts</td>
            </tr>
        <thead>
        <tbody>
            {%for category in expensecategory_list.all %}
                <tr>
                    <td> {{category.name}} </td>
                    <td> {{category.receipts.all|length}} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{%endblock content%}

receipts/templates/create.html
<!doctype html>
<html>
    <head>
        <title>Expnses</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new list</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/create_category.html
<!doctype html>
<html>
    <head>
        <title>Expenses</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create Category</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipt.html
{%extends 'base.html'%}
{%block content%}
<main>
    <h1>My Receipts </h1>
    <table>
        <thead>
            <tr>
                <td>Vendor</td>
                <td>Total</td>
                <td>Tax</td>
                <td>Date</td>
                <td>Category</td>
                <td>Account</td>
            </tr>
        <thead>
        <tbody>
            {%for item in receipt_list %}
                <tr>
                    <td> {{item.vendor}} </td>
                    <td> {{item.total}} </td>
                    <td> {{item.tax}} </td>
                    <td> {{item.date|date:"m-d-Y"}} </td>
                    <td> {{item.purchaser}} </td>
                    <td>{{item.category}} </td>
                    <td> {{item.account}} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{%endblock content%}